# ðŸš¨ Attention, le code prÃ©sent dans ce fichier contient volontairement de nombreuses imperfections :
# ðŸš¨ erreurs de conception, mauvaises pratiques de dÃ©veloppement logiciel, failles de sÃ©curitÃ© et de performance.
# ðŸš¨ Ce code servira de support Ã  un exercice de refactoring.
version: "3.9"

networks:
  rps:
    driver: bridge

services:
  api:
    image: node
    container_name: rps-api
    env_file:
      - .env
    working_dir: /usr/src/app
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    links:
      - db
    networks:
      - rps
  db:
    image: mariadb
    container_name: rps-db
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_USER=rps
      - MARIADB_DATABASE=rps
      - MARIADB_PASSWORD=azerty
    ports:
      - 3306:3306
    networks:
      - rps
  adminer:
    image: adminer
    container_name: rps-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 8181:8080
    networks:
      - rps
# ðŸš¨ Attention, le code prÃ©sent dans ce fichier contient volontairement de nombreuses imperfections :
# ðŸš¨ erreurs de conception, mauvaises pratiques de dÃ©veloppement logiciel, failles de sÃ©curitÃ© et de performance.
# ðŸš¨ Ce code servira de support Ã  un exercice de refactoring.
